//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCode_RSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string QuocGia { get; set; }
        public string NoiCuTru { get; set; }
        public string Avatar { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public int SoHieu { get; set; }
        public string SoBangCap { get; set; }
        public bool GioiTinh { get; set; }
        public string HinhThuc { get; set; }
        public string NganhDaoTao { get; set; }
        public string XepLoai { get; set; }
    }
}
